import { images } from "../../assets/catalog"

const moneyDatabase = [
  {
    codename: "philippines_one_cent",
    moneyName: "One Cent (₱0.01)",
    moneyDescription:
      "The obverse side of the coin feature the description 'Republika ng Pilipinas', the three stars and the sun (stylized representation of the Philippine flag), the denomination, year of minting, and mint mark, and the reverse side of the coin depicts the Xanthostemon verdugonianus (Mangkono), a plant endemic to the Philippines and the current logo of the Bangko Sentral ng Pilipinas. The composition is nickel-plated steel, has diameter of 15 mm, and mass of 1.9",
    obverse: images.OneCentObversePH,
    reverse: images.OneCentReversePH,
    conversion1: "Kuwait: 0.000055",
    conversion2: "British: 0.00014",
    conversion3: "Euro: 0.00016",
    conversion4: "Dollar: 0.00018",
  },
  {
    codename: "philippines_five_cents",
    moneyName: "Five Cents (₱0.05)",
    moneyDescription:
      "The obverse side of the coin feature the description 'Republika ng Pilipinas', the three stars and the sun (stylized representation of the Philippine flag), the denomination, year of minting, and mint mark, and the reverse side of the coin depicts the Hoya pubicalyx (Kapal-kapal baging), a plant endemic to the Philippines and the current logo of the Bangko Sentral ng Pilipinas. The composition is nickel-plated steel, has diameter of 16 mm, and mass of 2.2 grams.",
    obverse: images.FiveCentsObversePH,
    reverse: images.FiveCentsReversePH,
    conversion1: "Kuwait: 0.00027",
    conversion2: "British: 0.0007",
    conversion3: "Euro: 0.00082",
    conversion4: "Dollar: 0.00089",
  },
  {
    codename: "philippines_twenty_five_cents",
    moneyName: "Twenty Five Cents (₱0.25)",
    moneyDescription:
      "The obverse side of the coin feature the description 'Republika ng Pilipinas', the three stars and the sun (stylized representation of the Philippine flag), the denomination, year of minting, and mint mark, and the reverse side of the coin depicts the Hoya pubicalyx[19] (Kapal-kapal baging), a plant endemic to the Philippines and the current logo of the Bangko Sentral ng Pilipinas. The composition is nickel-plated steel, has diameter of 16 mm, and mass of 2.2 grams.",
    obverse: images.TwentyFiveCentsObversePH,
    reverse: images.TwentyFiveCentsReversePH,
    conversion1: "Kuwait: 0.0014",
    conversion2: "British: 0.0035",
    conversion3: "Euro: 0.0041",
    conversion4: "Dollar: 0.0045",
  },
  {
    codename: "philippines_one_peso",
    moneyName: "One Peso (₱1.00)",
    moneyDescription:
      "The obverse side of the coin feature the description 'Republika ng Pilipinas', José Rizal, a national hero of the Philippines, the denomination, year of minting, and mint mark, and the reverse side of the coin depicts the Vanda sanderiana (Waling-Waling), a plant endemic to the Philippines and the current logo of the Bangko Sentral ng Pilipinas. The composition is nickel-plated steel, has diameter of 23 mm, and mass of 6 grams.",
    obverse: images.OnePesoObversePH,
    reverse: images.OnePesoReversePH,
    conversion1: "Kuwait: 0.0055",
    conversion2: "British: 0.014",
    conversion3: "Euro: 0.016",
    conversion4: "Dollar: 0.018",
  },
  {
    codename: "philippines_five_pesos",
    moneyName: "Five Pesos (₱5.00)",
    moneyDescription:
      "The obverse side of the coin feature the description 'Republika ng Pilipinas', Andrés Bonifacio, a national hero of the Philippines, the denomination, year of minting, and mint mark, and the reverse side of the coin depicts the Strongylodon macrobotrys (Tayabak), a plant endemic to the Philippines and the current logo of the Bangko Sentral ng Pilipinas. The composition is nickel-plated steel, has diameter of 25 mm, and mass of 7.4 grams. Due to the confusion of the 5-piso coin bearing similarities with the 1-piso coin (mainly caused by its similar size), the Bangko Sentral ng Pilipinas has reissued the 5-piso coin in a nonagonal (9-sided shape) into circulation on December 17, 2019.",
    obverse: images.FivePesosObversePH,
    reverse: images.FivePesosReversePH,
    conversion1: "Kuwait: 0.027",
    conversion2: "British: 0.070",
    conversion3: "Euro: 0.082",
    conversion4: "Dollar: 0.089",
  },
  {
    codename: "philippines_ten_pesos",
    moneyName: "Ten Pesos (₱10.00)",
    moneyDescription:
      "The obverse side of the coin feature the description 'Republika ng Pilipinas', Apolinario Mabini, a national hero of the Philippines, the denomination, year of minting, and mint mark, and the reverse side of the coin depicts the Medinilla magnifica (Kapa-kapa), a plant endemic to the Philippines and the current logo of the Bangko Sentral ng Pilipinas. The composition is nickel-plated steel, has diameter of 27 mm, and mass of 8 grams. This is the third edge inscription coin used in the Philippines in common circulation after the 1897 one piso coin which edge is fleur-de-iles and the 50 sentimo coin in 1880–1885 which is inscripted LEY PATRIA REY which means 'Law, homeland, king'.",
    obverse: images.TenPesosObversePH,
    reverse: images.TenPesosReversePH,
    conversion1: "Kuwait: 0.055",
    conversion2: "British: 0.14",
    conversion3: "Euro: 0.16",
    conversion4: "Dollar: 0.18",
  },
  {
    codename: "philippines_twenty_pesos",
    moneyName: "Twenty Pesos Coin (₱20.00)",
    moneyDescription:
      "The 20 piso banknote will be changed into a coin that will be released in December 2019 to solve the overuse of this banknote that only takes a year to replace it with a new banknote based on a research by the University of the Philippines. The coin is bi-metallic, with a bronze-plated steel outer ring and a nickel-plated steel center plug, and is the second bi-metallic coin issued by the Bangko Sentral ng Pilipinas. The obverse side of the coin features a portrait of Philippine President Manuel Quezon and the reverse side of the coin depict the Scyphiphora (Nilad), Malacañang Palace, the official residence and workplace of the President of the Philippines and the current logo of the Bangko Sentral ng Pilipinas. One notable feature is the edge inscription, with the initial 'BSP' at six angles. This is the fourth edge inscription coin used in the Philippines in common circulation.",
    obverse: images.TwentyPesosObversePH,
    reverse: images.TwentyPesosReversePH,
    conversion1: "Kuwait: 0.11",
    conversion2: "British: 0.28",
    conversion3: "Euro: 0.33",
    conversion4: "Dollar: 0.36",
  },
  {
    codename: "philippines_fifty_pesos",
    moneyName: "Fifty Pesos (₱50.00)",
    moneyDescription:
      "Colored red, the main designs shown on the front of the note depict a portrait of Philippine president Sergio Osmeña and images tied to him, one depicting the First Philippine Assembly in 1907 and the other the Leyte Landing. The main designs on the back show Taal Lake, the Giant Trevally (locally known as Maliputo) (Caranx ignobilis) and an embroidery design from Batangas province.",
    obverse: images.FiftyPesosPaperObversePH,
    reverse: images.FiftyPesosPaperReversePH,
    conversion1: "Kuwait: 0.27",
    conversion2: "British: 0.70",
    conversion3: "Euro: 0.82",
    conversion4: "Dollar: 0.89",
  },
  {
    codename: "philippines_one_hundred_pesos",
    moneyName: "One Hundred Pesos (₱100.00)",
    moneyDescription:
      "Colored violet, the main designs for this denomination on the front depict a portrait of Philippine president Manuel A. Roxas and images associated with Roxas, including the founding of the Central Bank of the Philippines (Bangko Sentral ng Pilipinas) in 1949 and the Inauguration of the Third Philippine Republic on July 4, 1946. The main designs shown on the back feature the Mayon Volcano, the Whale Shark (locally known as Butanding, scientific name Rhincodon typus) and a weave design from Bicol. The original version, issued from 2010 to 2016, included a blue underprint. Notes issued from 2016 onwards have a strong mauve or violet color, due to complaints that the color of the 100 pesos note is almost indistinguishable from the 1,000 pesos note.",
    obverse: images.OneHundredPesosPaperObversePH,
    reverse: images.OneHundredPesosPaperReversePH,
    conversion1: "Kuwait: 0.55",
    conversion2: "British: 1.41",
    conversion3: "Euro: 1.65",
    conversion4: "Dollar: 1.78",
  },
  {
    codename: "philippines_two_hundred_pesos",
    moneyName: "Two Hundred Pesos (₱200.00)",
    moneyDescription:
      "Colored green, the main designs of the front of the note feature a portrait of Philippine president Diosdado P. Macapagal, along with images associated with Macapagal, including the EDSA People Power 2001, the Aguinaldo Shrine in Kawit, Cavite and the Barasoain Church in Malolos, Bulacan. The main designs on the back of the note feature the Chocolate Hills in Bohol, the Philippine tarsier (Tarsius syrichta), and a weave design from the Visayas. The main designs on the front of the note were used from 2010 to 2017. The 2017 issue features images showing the Declaration of Philippine Independence in Kawit, Cavite, and the Opening of the Malolos Congress in Barasoain Church, Malolos, Bulacan.",
    obverse: images.TwoHundredPesosPaperObversePH,
    reverse: images.TwoHundredPesosPaperReversePH,
    conversion1: "Kuwait: 1.10",
    conversion2: "British: 2.82",
    conversion3: "Euro: 3.29",
    conversion4: "Dollar: 3.56",
  },
  {
    codename: "philippines_five_hundred_pesos",
    moneyName: "Five Hundred Pesos (₱500.00)",
    moneyDescription:
      "Colored yellow, the main designs on the front of the note feature the dual portraits of Philippine Senator Benigno Aquino Jr. and his wife, Philippine president Corazon C. Aquino. Also on the front of the note are images associated to the couple, the image of the 1986 People Power Revolution and the Benigno Aquino Jr. monument in Makati. The main designs on the back of the note feature the Subterranean River National Park, the Blue-naped parrot (Tanygnathus lucionensis), and a cloth design from the Southern Philippines.",
    obverse: images.FiveHundredPesosPaperObversePH,
    reverse: images.FiveHundredPesosPaperReversePH,
    conversion1: "Kuwait: 2.74",
    conversion2: "British: 7.05",
    conversion3: "Euro: 8.23",
    conversion4: "Dollar: 8.90",
  },
  {
    codename: "philippines_one_thousand_pesos",
    moneyName: "One Thousand Pesos (₱1,000.00)",
    moneyDescription:
      "Colored light-blue, the main designs on the front of the note feature the trio portraits of José Abad Santos, Vicente Lim and Josefa Llanes Escoda. Also on the front of the note is an image of the Centennial celebration of Philippine independence. The main designs on the back of the note feature the Tubbataha Reefs Natural Park, the South Sea Pearl (Pinctada maxima), and a cloth design from the Mindanao design for T'nalak (Ikat-dyed abaca). The original issue from 2010 to 2017 featured the Order of Lakandula (erroneously labelled as 'Medal of Honor') and its description on the front. Notes issued from 2017 onwards omit both the medal and its description. This April 2022, the BSP in partnership with the Reserve Bank of Australia, will release a limited trial polymer version of the 1000-piso banknote, completely removing the three portraits of the figureheads and instead replacing it with an image of the Philippine Eagle with a clear window of Sampaguita, the national flower of the Philippines. The banknote is also the first to be printed which features the 2020 logo of the Bangko Sentral ng Pilipinas, which has received much criticism from the general public. In an interview, Bangko Sentral ng Pilipinas Governor Benjamin Diokno stated that 'The new series will focus on fauna and flora in the Philippines.'",
    obverse: images.OneThousandHundredPesosPaperObversePH,
    reverse: images.OneThousandHundredPesosPaperReversePH,
    conversion1: "Kuwait: 5.48",
    conversion2: "British: 14.09",
    conversion3: "Euro: 16.45",
    conversion4: "Dollar: 17.80",
  },
  {
    codename: "british_five_note",
    moneyName: "Five Note (5£)",
    moneyDescription:
      "The banknote of five pounds is a fundamental denomination in the British currency, which has significant people and monuments on both its frontispiece sides. The obverse generally includes a portrait of Queen Elizabeth II, while the reverse often showcases other figures like famous British people or known buildings and places. The five-pound banknote is also a recognizable symbol of Britain’s culture and history, serving the daily economic needs while preserving its cultural identity.",
    obverse: images.FiveNoteObverse,
    reverse: images.FiveNoteReverse,
    conversion1: "Kuwait: 1.94",
    conversion2: "Peso: 354.76",
    conversion3: "Euro: 5.84",
    conversion4: "Dollar: 6.32",
  },
  {
    codename: "british_ten_note",
    moneyName: "Ten Note (10£)",
    moneyDescription:
      "The ten-pound banknote, which is an integral part of the British currency has a portrait of Queen Elizabeth II on one side and some British symbols or historical figures are shown on the other. For instance, such symbols could be iconic landmarks that are symbolical of the nation’s cultural heritage and values. Thus, the ten-pound banknote with an elaborate pattern and high defensibility forms a popular medium of exchange indicating numerous riches stemming from British history & culture as well as allowing day to day activities across Great Britain.",
    obverse: images.TenNoteObverse,
    reverse: images.TenNoteReverse,
    conversion1: "Kuwait: 3.89",
    conversion2: "Peso: 709.53",
    conversion3: "Euro: 11.69",
    conversion4: "Dollar: 12.63",
  },
  {
    codename: "british_twenty_note",
    moneyName: "Twenty Note (20£)",
    moneyDescription:
      "The twenty-pound banknote, a staple of British money, features the profile of Queen Elizabeth II on the face and various iconic symbols or historical figures seen in reverse as part representation for England’s fabulous history. The quality of the banknote design and manufacture make it a widely accepted means of exchange, embodying British culture facilitating business throughout England.",
    obverse: images.TwentyNoteObverse,
    reverse: images.TwentyNoteReverse,
    conversion1: "Kuwait: 7.77",
    conversion2: "Peso: 1419.05",
    conversion3: "Euro: 23.38",
    conversion4: "Dollar: 25.27",
  },
  {
    codename: "british_one_pound",
    moneyName: "One Pound (1£)",
    moneyDescription:
      "The one pound coin has been a fixture of British currency for some time now and features the effigy Queen Elizabeth II on the obverse, together with various insignias such as those dedicated to Royal Coat of Arms or flowers that represent UK nations. The coin is made of bimetallic material with detailed designs that act as currency for carrying out transactions but also present a heritage and identity image.",
    obverse: images.OnePoundObverse,
    reverse: images.OnePoundReverse,
    conversion1: "Kuwait: 0.39",
    conversion2: "Peso: 70.95",
    conversion3: "Euro: 1.17",
    conversion4: "Dollar: 1.26",
  },
  {
    codename: "british_two_pounds",
    moneyName: "Two Pound (2£)",
    moneyDescription:
      "The famous two-pound coin, a classical element of the British currency has queen Elizabeth II’s effigy on its obverse and different motifs in reverse varying from historical figures to commemorative themes. The coin is a bi-metallic construction with intricate detailing which makes it both an effective monetary instrument and cultural symbol of Britain, whose reverberations span across generations to reach borders.",
    obverse: images.TwoPoundObverse,
    reverse: images.TwoPoundReverse,
    conversion1: "Kuwait: 0.78",
    conversion2: "Peso: 141.91",
    conversion3: "Euro: 2.34",
    conversion4: "Dollar: 2.53",
  },
  {
    codename: "five_euro",
    moneyName: "Five Euro (5€)",
    moneyDescription:
      "The five-euro banknote is considered an icon of the Eurozone currency and depicts some characteristic architectural motifs from different parts of Europe, ranging across periods and styles. Its design symbolizes the cultural heritage and unity of EU. Broadly used in the everyday transactions, the banknote serves as a representation of common values unity and diversity throughout Euro zone.",
    obverse: images.FiveEuroObverse,
    reverse: images.FiveEuroReverse,
    conversion1: "Kuwait: 1.67",
    conversion2: "Peso: 304.05",
    conversion3: "British: 4.28",
    conversion4: "Dollar: 5.40",
  },
  {
    codename: "ten_euro",
    moneyName: "Ten Euro (10€)",
    moneyDescription:
      "The ten euro banknote is one of the most important denominations in terms of values that make Eurozone currency units, architectural motifs from different periods and styles are shown on this introduction for architecture across Europe indicating strong cultural unity typical to the continent. So widely used for everyday business transactions is the banknote that it represents perfectly well some of the European Union’s founding features such as cooperation and heterogeneity, which through economic union ensures integration economically across member states.",
    obverse: images.TenEuroObverse,
    reverse: images.TenEuroReverse,
    conversion1: "Kuwait: 3.34",
    conversion2: "Peso: 608.10",
    conversion3: "British: 8.55",
    conversion4: "Dollar: 10.81",
  },
  {
    codename: "twenty_euro",
    moneyName: "Twenty Euro (20€)",
    moneyDescription:
      "The twenty euro banknote constituting the regalia of the Eurozone currency depicts architectural motives popular in different times from all around Europe symbolizing its rich culture and unity. The banknote is one that spread rapidly, has made smooth transaction possible and tells of the spirit of cooperation as well diversity in relation to European Union leading to sound economic bloc due for integration with a common identity among members.",
    obverse: images.TwentyEuroObverse,
    reverse: images.TwentyEuroReverse,
    conversion1: "Kuwait: 6.69",
    conversion2: "Peso: 1216.20",
    conversion3: "British: 17.11",
    conversion4: "Dollar: 21.61",
  },
  {
    codename: "one_euro",
    moneyName: "One Euro (1€)",
    moneyDescription:
      "The 1-euro coin that is at the core of the Eurozone currency has an unique design with a nickel-copper blanket and in addition to this, there is also a outer shell composed of bronze. On the obverse side of design, its seen that there are 12 stars signifying unity and a map for Europe while on this one it has the place to print every member states’ culture. The coin, which went widely around the world created a situation where anyone could effect business in seamless exchange; this gave economic integration as well as cultural diversity within the European Union.",
    obverse: images.OneEuroObverse,
    reverse: images.OneEuroReverse,
    conversion1: "Kuwait: 0.33",
    conversion2: "Peso: 60.81",
    conversion3: "British: 0.86",
    conversion4: "Dollar: 1.08",
  },
  {
    codename: "two_euro",
    moneyName: "Two Euro (2€)",
    moneyDescription:
      "The two euro coin constitutes a key element of the Eurozone currency and is made up bimetallic elements, with copper-nickel back bone which forms its core centering to nickel brass outer ring. On the obverse, there is a map of Europe with twelve stars representing unity among member countries and on its reverse side each country can emphasize their cultural heritage. Dubiously traded, the coin encourages smooth payments and represents principles of cooperation and diversity in European Union.",
    obverse: images.TwoEuroObverse,
    reverse: images.TwoEuroReverse,
    conversion1: "Kuwait: 0.67",
    conversion2: "Peso: 121.62",
    conversion3: "British: 1.71",
    conversion4: "Dollar: 2.16",
  },
  {
    codename: "kuwait_one_dinar",
    moneyName: "One Kuwaiti Dinar (1د.ك)",
    moneyDescription:
      "The one Kuwaiti dinar banknote, a popular denomination in Kuwait's currency, frequently displays a portrait of the ruling emir or major national landmarks on the obverse, while the reverse depicts cultural motifs, historical events, or imagery signifying Kuwait's legacy and progress. The one Kuwaiti dinar note, with its detailed design and durable substance, serves as a symbol of the country's economic stability and cultural identity, simplifying transactions while also expressing Kuwait's rich history and values.",
    obverse: images.OneKuwaitDinarObverse,
    reverse: images.OneKuwaitDinarReverse,
    conversion1: "Euro: 2.99",
    conversion2: "Peso: 181.77",
    conversion3: "British: 2.56",
    conversion4: "Dollar: 3.24",
  },
  {
    codename: "kuwait_five_dinar",
    moneyName: "Five Kuwaiti Dinar (5د.ك)",
    moneyDescription:
      "The five Kuwaiti dinar banknote, a key denomination in Kuwait's currency, often depicts the governing emir's face or famous locations on the obverse, while the reverse bears emblematic symbols of Kuwait's prosperity and legacy. The five Kuwaiti dinar note, with its detailed design and solid construction, reflects the country's economic power and cultural legacy, allowing for easy transactions while expressing Kuwait's dedication to progress and tradition.",
    obverse: images.FiveKuwaitDinarObverse,
    reverse: images.FiveKuwaitDinarReverse,
    conversion1: "Euro: 14.97",
    conversion2: "Peso: 908.85",
    conversion3: "British: 12.81",
    conversion4: "Dollar: 16.18",
  },
  {
    codename: "kuwait_ten_dinar",
    moneyName: "Ten Kuwaiti Dinar (5د.ك)",
    moneyDescription:
      "The ten Kuwaiti dinar banknote, a significant denomination in Kuwait's currency, frequently depicts the governing emir or notable national monuments on the obverse, while the reverse features emblems of Kuwaiti heritage and achievements. The ten Kuwaiti dinar note, with its elaborate design and robust construction, symbolizes the country's economic strength and cultural identity, simplifying transactions while also expressing Kuwait's devotion to prosperity and traditions.",
    obverse: images.TenKuwaitDinarObverse,
    reverse: images.TenKuwaitDinarReverse,
    conversion1: "Euro: 29.95",
    conversion2: "Peso: 1817.70",
    conversion3: "British: 25.62",
    conversion4: "Dollar: 32.36",
  },
  {
    codename: "kuwait_five_fils",
    moneyName: "Five Fils (5 KD)",
    moneyDescription:
      "The five fils coin is a popular denomination in several Middle Eastern nations, including Bahrain, Kuwait, and the United Arab Emirates. The coin, which is often made of non-precious metals such as brass, features the national emblem or symbol on one side and its numerical value on the reverse. With its small size and lightweight form, the five fils coin makes ordinary transactions easier, playing an important part in the local economy and monetary system.",
    obverse: images.FiveFilsObverse,
    reverse: images.FiveFilsReverse,
    conversion1: "Euro: 14.97",
    conversion2: "Peso: 908.85",
    conversion3: "British: 12.81",
    conversion4: "Dollar: 16.18",
  },
  {
    codename: "kuwait_ten_fils",
    moneyName: "Ten Fils (10 KD)",
    moneyDescription:
      "The 10 fils coin is a popular monetary denomination in the Middle East, particularly Bahrain, Kuwait, and the United Arab Emirates. Typically constructed of brass or comparable materials, it bears the country's insignia on one side and its value on the other. The 10 fils currency is small and lightweight, and it is frequently utilized for everyday transactions, helping to support the local economy and monetary system.",
    obverse: images.TenFilsObverse,
    reverse: images.TenFilsReverse,
    conversion1: "Euro: 29.95",
    conversion2: "Peso: 1817.70",
    conversion3: "British: 25.62",
    conversion4: "Dollar: 32.36",
  },
  {
    codename: "one_dollar",
    moneyName: "One Dollar (1$)",
    moneyDescription:
      "The obverse side of the one-dollar bill, which is a staple of American currency, usually features a portrait of a notable figure, such as George Washington. The reverse frequently includes iconic American emblems such as the Great Seal, the national motto, or historical sites. The one-dollar bill, with its distinctive design and sturdy material, is a widely accepted means of commerce, representing the ideas of American democracy and facilitating transactions throughout the United States.",
    obverse: images.OneDollarObverse,
    reverse: images.OneDollarReverse,
    conversion1: "Euro: 0.93",
    conversion2: "Peso: 56.16",
    conversion3: "British: 0.79",
    conversion4: "Kuwait: 0.31",
  },
  {
    codename: "two_dollars",
    moneyName: "Two Dollars (2$)",
    moneyDescription:
      "The two-dollar bill, a unique denomination in American money, often depicts a portrait of Thomas Jefferson on the obverse and the signing of the Declaration of Independence on the reverse. With its distinctive appearance and limited distribution, the two-dollar bill has historical value and is a collector's piece, as well as a valid form of cash for transactions throughout the United States.",
    obverse: images.TwoDollarObverse,
    reverse: images.TwoDollarReverse,
    conversion1: "Euro: 1.85",
    conversion2: "Peso: 112.33",
    conversion3: "British: 1.58",
    conversion4: "Kuwait: 0.62",
  },
  {
    codename: "five_dollars",
    moneyName: "Five Dollars (5$)",
    moneyDescription:
      "The five-dollar bill, a prevalent denomination in American currency, often bears the portrait of Abraham Lincoln on the obverse side and iconic American symbols or historical events on the reverse. These symbols may include representations of the Lincoln Memorial, images of national landmarks, or scenes commemorating pivotal moments in American history. With its recognizable design and durable construction, the five-dollar bill serves as a widely accepted medium of exchange, reflecting the values and heritage of the United States while facilitating transactions nationwide.",
    obverse: images.FiveDollarObverse,
    reverse: images.FiveDollarReverse,
    conversion1: "Euro: 4.63",
    conversion2: "Peso: 280.82",
    conversion3: "British: 3.96",
    conversion4: "Kuwait: 1.54",
  },
  {
    codename: "nickel",
    moneyName: "Nickel",
    moneyDescription:
      "The nickel coin in the United States, worth five cents, often depicts Thomas Jefferson's likeness on the obverse and the famous image of Monticello, Jefferson's historic plantation, on the reverse. The nickel coin, made of a copper-nickel alloy, stands out for its smooth edge and unusual size. The nickel coin, widely circulated and utilized in everyday transactions, is a fundamental unit of American currency that reflects the country's history and enduring values.",
    obverse: images.NickelObverse,
    reverse: images.NickelReverse,
    conversion1: "Euro: 0.046",
    conversion2: "Peso: 2.81",
    conversion3: "British: 0.040",
    conversion4: "Kuwait: 0.015",
  },
  {
    codename: "penny",
    moneyName: "Penny",
    moneyDescription:
      "The penny coin of the United States, worth one cent, prominently shows Abraham Lincoln's profile on the obverse and the Lincoln Memorial on the reverse. The penny, made primarily of zinc with a copper plating, is distinguished by its reddish hue and diminutive size. The penny, which is widely circulated and frequently used in daily transactions, is symbolic of American history and tenacity, reflecting the country's enduring values and principles.",
    obverse: images.PennyObverse,
    reverse: images.PennyReverse,
    conversion1: "Euro: 0.0093",
    conversion2: "Peso: 0.56",
    conversion3: "British: 0.0079",
    conversion4: "Kuwait: 0.0031",
  },
]

export default moneyDatabase
